spring.application.name=persistence


spring.web.error.include-message=never
spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false
spring.web.error.include-binding-errors=never
